Include tasks in coverage
WildMeOrg/houston pull request #59
Opened 2021-02-23 21:18 UTC by karenc

## Pull Request Overview

Even though there are no tests for tasks, we can still try running the tasks and including them in coverage.

- Fix app.db.current for alembic 1.5.0+
- Add tasks/ to coverage in .coveragerc
- Include coverage for db migrations tasks in testing workflow
- Exclude code for older versions of alembic in db tasks from coverage
- Add coverage for various invoke tasks in testing workflow
- Exclude (most) ImportError from coverage
- Change User.version from Integer to BigInteger
- Change Organization.version from Integer to BigInteger
- Remove unused code in tasks/app/env.py

**Pull Request Checklist**
- [x] Ensure that the PR is properly formatted
  - Example: All lint checks are passing
- [x] Ensure that the PR is properly rebased
  - Example: The PR is rebased on `develop` (commit: `<insert develop commit hash>`)
- [x] Ensure that the PR uses a consolidated database migration
  - Example: One database migration is proposed (revision `<insert develop revision>` -> `<insert new revision>`)
- [x] Ensure that the PR is properly tested
  - Example: All automated tests are passing
- [x] Ensure that the PR is properly sanitized
  - Example: No sensitive data or large content was added to this PR
- [ ] Ensure that the PR is properly reviewed

2021-02-23 23:19 UTC, bluemellophone requested changes
Largely approve, some small issues to address:
1. Can we merge the two database migrations into a single version?  If not, let's at least fix the file name for `migrations/versions/626759c27d1f_change_organization_version_to_.py`
2. Should the file `run_tasks_for_coverage.sh` be moved to `scripts/`?
3. When new invoke tasks are added will we need to add test examples to `run_tasks_for_coverage.sh`?  Is there a way to add more implicit documentation testing to invoke commands using JC's `xdoctest` module or add them to the test folder directly?

2021-02-24 18:44 UTC, karenc commented
@bluemellophone 

>  1. Can we merge the two database migrations into a single version?  If not, let's at least fix the file name for `migrations/versions/626759c27d1f_change_organization_version_to_.py`

I merged them into one migration.  It's the same kind of migration for the same column so not a problem.  By the way the filename got truncated by `app.db.migrate -m "Change organization version to BigInteger"` :facepalm:

>  2. Should the file `run_tasks_for_coverage.sh` be moved to `scripts/`?

Yeah, that's a good idea.

>  3. When new invoke tasks are added will we need to add test examples to `run_tasks_for_coverage.sh`?  Is there a way to add more implicit documentation testing to invoke commands using JC's `xdoctest` module or add them to the test folder directly?

It's better to add tests instead of adding to this file.  It's kind of temporary for now.

2021-02-24 19:09 UTC, bluemellophone approved these changes

2021-02-24 19:12 UTC, bluemellophone approved these changes

2021-02-24 19:58 UTC, merged